#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix:   /connect


google_login:
  path: /login/check-google

app_logout:
  path: /logout
